var userName = "abuzar";
console.log(userName);
userName = "younas";
console.log(userName);
var firstNum = 2;
var secondNumber = 30;
var thirdNumber = firstNum * secondNumber;
console.log(thirdNumber);
var num = 78;
console.log(num);
